# Generated by Django 4.0 on 2021-12-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=64)),
                ('anime_desc', models.TextField()),
                ('anime_rank', models.IntegerField()),
                ('anime_country', models.CharField(max_length=64)),
                ('anime_type', models.CharField(max_length=64)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('anime_watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
